"""Minimal SDS PDF generator (stub) to emit CLP-style sheets."""

from __future__ import annotations

from typing import Iterable, Mapping, Any, List, Dict
from pathlib import Path

from fpdf import FPDF

from .hazard_calculator import CalculatedHazard
from ..config.constants import SDS_SECTIONS
from ..utils.logger import get_logger

logger = get_logger(__name__)


def _as_lines(value: Any) -> str:
    if value is None:
        return "Not provided"
    if isinstance(value, str):
        return value
    if isinstance(value, Iterable):
        return ", ".join(str(v) for v in value)
    return str(value)


class SDSGenerator:
    """Create a simple CLP-aligned SDS PDF from structured data."""

    def __init__(self) -> None:
        # Titles for 16 sections (Portuguese labels kept for compatibility)
        self.sections = SDS_SECTIONS
        self.pictogram_names: Dict[str, str] = {
            "GHS01": "Explosive",
            "GHS02": "Flammable",
            "GHS03": "Oxidizing",
            "GHS04": "Gas under pressure",
            "GHS05": "Corrosive",
            "GHS06": "Toxic",
            "GHS07": "Harmful/Irritant",
            "GHS08": "Health hazard",
            "GHS09": "Environmental",
        }

    def generate(
        self,
        data: Mapping[str, Any],
        hazards: List[CalculatedHazard] | None,
        output_path: Path,
    ) -> Path:
        """
        Generate an SDS PDF.

        Args:
            data: mapping with keys like product_name, cas_number, hazard_class,
                  h_statements, p_statements, composition, supplier, emergency_phone.
            hazards: optional list of CalculatedHazard from HazardCalculator.
            output_path: where to write the PDF.
        """
        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 14)

        title = data.get("product_name") or "Safety Data Sheet"
        pdf.cell(0, 10, f"SDS - {title}", ln=1)
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(0, 8, f"CAS: {data.get('cas_number', 'Not provided')}", ln=1)
        pdf.cell(0, 8, f"Hazard Class: {data.get('hazard_class', 'Not provided')}", ln=1)
        pdf.cell(0, 8, f"Supplier: {data.get('supplier', 'Not provided')}", ln=1)
        pdf.cell(0, 8, f"Emergency phone: {data.get('emergency_phone', 'Not provided')}", ln=1)
        pdf.ln(4)

        # Section helper
        def section(idx: int, body: str) -> None:
            name = self.sections.get(idx, f"Section {idx}")
            pdf.set_font("Helvetica", "B", 12)
            pdf.cell(0, 8, f"{idx}. {name}", ln=1)
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(0, 6, body or "Not provided")
            pdf.ln(1)

        # Section bodies
        section(
            1,
            f"Product identifier: {title}\nCAS: {data.get('cas_number', 'Not provided')}\n"
            f"Recommended use: {data.get('use', 'Not provided')}\n"
            f"Supplier: {data.get('supplier', 'Not provided')}\n"
            f"Emergency phone: {data.get('emergency_phone', 'Not provided')}",
        )
        section(
            2,
            f"Hazard classification: {data.get('hazard_class', 'Not provided')}\n"
            f"H statements: {_as_lines(data.get('h_statements'))}\n"
            f"P statements: {_as_lines(data.get('p_statements'))}\n"
            f"Pictograms: {_as_lines(self._render_pictograms(data.get('pictograms')))}",
        )
        section(
            3,
            f"Composition: {_as_lines(data.get('composition'))}",
        )
        section(4, data.get("first_aid", "Not provided"))
        section(5, data.get("fire_fighting", "Not provided"))
        section(6, data.get("spill_response", "Not provided"))
        section(7, data.get("handling_storage", "Not provided"))
        section(8, data.get("exposure_controls", "Not provided"))
        section(9, _as_lines(data.get("physical_properties", "Not provided")))
        section(10, data.get("stability_reactivity", "Not provided"))
        section(11, data.get("toxicology", "Not provided"))
        section(12, data.get("ecology", "Not provided"))
        section(13, data.get("disposal", "Not provided"))
        section(14, data.get("transport", "Not provided"))
        section(15, data.get("regulatory", "Not provided"))
        section(16, data.get("other_info", "Generated by RAG_SDS_MATRIX"))

        # Optional hazard calculator summary
        if hazards:
            pdf.add_page()
            pdf.set_font("Helvetica", "B", 12)
            pdf.cell(0, 8, "Calculated Hazard Summary", ln=1)
            pdf.set_font("Helvetica", "", 10)
            for hz in hazards:
                pdf.multi_cell(
                    0,
                    6,
                    f"{hz.hazard_code} (Cat {hz.category}) - {hz.basis}",
                )

        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        pdf.output(str(output_path))
        logger.info("Generated SDS PDF: %s", output_path)
        return output_path

    def _render_pictograms(self, codes: Any) -> List[str]:
        if not codes:
            return []
        if isinstance(codes, str):
            codes = [c.strip() for c in codes.split(",") if c.strip()]
        rendered = []
        for code in codes:
            name = self.pictogram_names.get(code.strip().upper())
            rendered.append(f"{code} ({name})" if name else code)
        return rendered
